<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>8BitMode</AssemblyName>
    <RootNamespace>EightBitMode</RootNamespace>
    <Optimize>true</Optimize>
    <OutputPath>..\Assemblies\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\RimWorldRefs\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\RimWorldRefs\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\RimWorldRefs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\RimWorldRefs\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\RimWorldRefs\0Harmony.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
